---
apiVersion: v1
kind: Service
metadata:
  name: stock
  labels:
    app: stock
spec:
  type: NodePort
  selector:
    app: stock
  ports:
  - protocol: TCP
    port: 8030
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: stock
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stock
    spec:
      containers:
      - name: stock
        image: javashop.stock:latest
        ports:
        - containerPort: 8030
        env:
          - name: SIGNALFX_AGENT_HOST
            valueFrom: 
              fieldRef:
                fieldPath:  status.hostIP
          - name: OTEL_EXPORTER_JAEGER_ENDPOINT
            value: http://$(SIGNALFX_AGENT_HOST):9080/v1/trace
           #livenessProbe:
           #httpGet:
           #path: /health
           # port: 8030
           #initialDelaySeconds: 30
           #timeoutSeconds: 1
