---
apiVersion: v1
kind: Service
metadata:
  name: shop
  labels:
    app: shop
spec:
  type: NodePort
  selector:
    app: shop
  ports:
  - protocol: TCP
    port: 8010
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: shop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: shop
    spec:
      containers:
      - name: shop
        image: shabushabu/javashop.shop:1.22
        ports:
        - containerPort: 8010
        env:

          - name: SIGNALFX_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP

          - name: OTEL_EXPORTER_JAEGER_ENDPOINT
            value: http://$(SIGNALFX_AGENT_HOST):9080/v1/trace
                
                
                #livenessProbe:
                # httpGet:
                #path: /health
                #port: 8010
                #initialDelaySeconds: 30
                #timeoutSeconds: 1 

